name: Sync Medium Posts

on:
  schedule:
    - cron: '17 6 * * 1'  # Every Monday 06:17 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Import Medium RSS
        env:
          FEED_URL: ${{ secrets.MEDIUM_FEED_URL != '' && secrets.MEDIUM_FEED_URL || vars.MEDIUM_FEED_URL }}
        run: |
          if [ -z "${FEED_URL}" ]; then
            echo "FEED_URL is not set. Define repo Secret MEDIUM_FEED_URL or Variable MEDIUM_FEED_URL." >&2
            exit 1
          fi
          python scripts/sync_medium.py --feed "${FEED_URL}"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(content): import Medium posts"
            git push
          else
            echo "No changes to commit"
          fi
